name: pt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  health : ^13.1.1
  permission_handler: ^12.0.1
  english_words: ^4.0.0
  provider: ^6.1.5
  http: ^1.2.1                
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3        
  flutter_riverpod: ^2.5.1      
  google_generative_ai: ^0.4.7
  image_picker: ^1.1.1
  mime: ^1.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  crypto: ^3.0.3
  mobile_scanner: ^7.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^7.1.1
  cloud_firestore: ^6.0.0
  camera: ^0.10.6
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons: ^0.11.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9          
  hive_generator: ^2.0.1      


flutter:
  uses-material-design: true